apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: akstest-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        app: akstest-frontend
        service: frontend
    spec:
      containers:
        - name: frontend
          image: xfacr01.azurecr.io/xfdemo/akstestfrontend:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: akstest-frontend
    service: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: frontend