apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: akstest-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
  template:
    metadata:
      labels:
        app: akstest-backend
        service: backend
    spec:
      containers:
        - name: backend
          image: xlacr01.azurecr.io/xfdemo/akstestbackend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: akstest-backend
    service: backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: backend